### ISSUE TITLE
Is it possible to pass a list through an env var?

### ISSUE THREAD

**Issue by steve-chavez** [robx/configurator-pg#3]
Having this config key:
```
raw-media-types = ["one", "two"]
```

I want to pass it through an env var like:
```
raw-media-types = "$(LIST)"
```

So I do `export LIST=["one", "two"]`.
This will give an error:
```
Error parsing config file: expected a list
```

Having `"$(LIST)"` without quotes gives the following error: `Error parsing config file: parsing support/configs/config: endOfInput`

Is there some other way to pass the list to the env var?

**Comment by robx** [comment]
No, interpolation currently treats all environment variables as plain strings. (This code is pretty much directly lifted from configurator-ng.)

The relevant part of the code is here: https://github.com/robx/configurator-pg/blob/master/src/Data/Configurator/Load.hs#L55

**Comment by steve-chavez** [comment]
Hmm, I see. Maybe surrounding brackets `"[]"` in the string could be parsed an interpreted as a list.

**Comment by robx** [comment]
That wouldn't be a backwards compatible change, though.

I'm not sure that developing this library further would be a worthwhile effort. That said, happy to apply patches.

(In that case, it might be a good idea to tie the interface more closely to what postgrest wants to do with it. In particular, make it so that postgrest doesn't need to perform the string->number coercion it currently does, and bring the file interpolation from postgrest/main/Main.hs into configurator-pg as some more general interpolation thing.)

**Comment by steve-chavez** [comment]
@robx I understand. Maybe the simplest thing would be to patch PostgREST and not use a list for `raw-media-types`, instead having it be like:

```
raw-media-types = "text/html, image/png"
```

**Comment by steve-chavez** [comment]
Will fix in PostgREST.
